version: '2'

services:
  domain-router:
    image: wilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "vhost.d:/etc/nginx/vhost.d"
      - "certs:/etc/nginx/certs:ro"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    restart: always
    
   domain-router-companion:
     image: jrcs/letsencrypt-nginx-proxy-companion
     volumes:
       - "certs:/domain/certs:/etc/nginx/certs:rw"
       - "/var/run/docker.sock/var/run/docker.sock:ro"
     volumes_from:
       - container:domain-router
