version: '2'

services:
  domain-router:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./vhost.d:/etc/nginx/vhost.d
      - ./certs:/etc/nginx/certs:ro
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    
  domain-router-companion:
     image: jrcs/letsencrypt-nginx-proxy-companion
     volumes:
       - ./certs:/etc/nginx/certs:rw
       - /var/run/docker.sock:/var/run/docker.sock:ro
     volumes_from:
       - domain-router
     depends_on:
       - "domain-router"
     restart: always

  own-registry:
    image: registry:2
    environment:
      - "REGISTRY_HTTP_TLS_CERTIFICATE=/certs/${DOMAIN_NAME}.crt"
      - "REGISTRY_HTTP_TLS_KEY=/certs/${DOMAIN_NAME}.key"
      - "VIRTUAL_HOST=${DOMAIN_NAME}"
      - "VIRTUAL_PORT=5000"
      - "VIRTUAL_PROTO=https"
      - "LETSENCRYPT_HOST=${DOMAIN_NAME}"
      - "LETSENCRYPT_EMAIL=${EMAIL_ADDRESS}"
    depends_on:
       - "domain-router-companion"
    restart: always
